language: ruby
services:
  - docker

env:
  - IMAGE_NAME=catone/trips_planner

before_install:
  - sudo apt-get -y install sshpass
addons:
  apt:
    update: true

script:
  - docker pull "$IMAGE_NAME" || true
  - docker build --cache-from "$IMAGE_NAME" 
      --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" 
      --build-arg VCS_REF="$TRAVIS_COMMIT" 
      -t "build/$IMAGE_NAME" -f ./Dockerfile .
  - docker run -d -P --name temp "build/$IMAGE_NAME"
  - docker rm -f temp || vitrue

after_success:
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD_SECURE";
    docker tag "build/$IMAGE_NAME" "$IMAGE_NAME:backend";
    docker push "$IMAGE_NAME:backend";
    sshpass -p "$SERVER_PASSWD" ssh  -o StrictHostKeyChecking=no "$SERVER_USER"@49.235.244.252 "rm -rf Backend/ && git clone https://github.com/TripsPlanner/Backend && cd Backend && git checkout devops && echo -e "DB_PORT="$DB_PORT" > .env && echo -e DB_SERVER="$DB_SERVER" \n DB_PASSWD="$DB_PASSWD" \n DB_USER="$DB_USER" \n " >> .env && source .env && docker-compose up -d";
    docker ps

